id: I7260B3DB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T08:05:30+00:00'
last_modified: '2022-06-08T06:33:06.287603+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS20236
  title: སྐོམ་སེལ་བདུད་རྩིའི་ཆུ་རྒྱུན། དེབ་དང་པོ་ནས་དགུ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    3B37:
      image_group_id: I8LS20787
      title: ''
      total_pages: 73
      order: 1
      base_file: 3B37.txt
    '5045':
      image_group_id: I8LS20788
      title: ''
      total_pages: 69
      order: 2
      base_file: 5045.txt
    D1B1:
      image_group_id: I8LS20789
      title: ''
      total_pages: 85
      order: 3
      base_file: D1B1.txt
    '6676':
      image_group_id: I8LS20790
      title: ''
      total_pages: 113
      order: 4
      base_file: 6676.txt
    6D19:
      image_group_id: I8LS20791
      title: ''
      total_pages: 129
      order: 5
      base_file: 6D19.txt
    277F:
      image_group_id: I8LS20792
      title: ''
      total_pages: 153
      order: 6
      base_file: 277F.txt
    51B7:
      image_group_id: I8LS20793
      title: ''
      total_pages: 157
      order: 7
      base_file: 51B7.txt
    '7849':
      image_group_id: I8LS20794
      title: ''
      total_pages: 185
      order: 8
      base_file: 7849.txt
    CCC2:
      image_group_id: I8LS20795
      title: ''
      total_pages: 229
      order: 9
      base_file: CCC2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
